kubectl delete -f UserService/k8s/
kubectl delete -f AuthService/k8s/
kubectl delete -f StreamService/k8s/
kubectl delete -f AnalyticsService/k8s/
kubectl delete -f RecommendationService/k8s/
kubectl delete -f Database/PostgreSQL/
kubectl delete -f Database/Redis/
kubectl delete -f Nginx-RTMP/k8s
kubectl delete -f DatabaseManagementService/k8s