apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          # Route to Angular Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: 80

          # Route to User Service
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: user-db-handler
                port:
                  number: 80

          # Route to Auth Service
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

          # Route to Stream Db Handler Service
          - path: /api/streamdbhandler
            pathType: Prefix
            backend:
              service:
                name: stream-db-handler
                port:
                  number: 80

          # Route to Stream Service
          - path: /api/streamservice
            pathType: Prefix
            backend:
              service:
                name: stream-service
                port:
                  number: 80

          # Route to Viewer Service
          - path: /api/viewer
            pathType: Prefix
            backend:
              service:
                name: viewer-service
                port:
                  number: 80

          # Route to Follower Service
          - path: /api/follower
            pathType: Prefix
            backend:
              service:
                name: follower-service
                port:
                  number: 80

          # Route to Database Management Service
          - path: /api/dbmanagement
            pathType: Prefix
            backend:
              service:
                name: db-management
                port:
                  number: 80
          - path: /hls
            pathType: Prefix
            backend:
              service:
                name: nginx-rtmp-service
                port:
                  number: 8080

            
        
