apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
  labels:
    app: stream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: stream-service
        image: bugapeti/streamservice-k8s:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: Jwt__ServiceToken
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: service-token
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret-key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-audience
        - name: Jwt__ExpiryMinutes
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-expiry-minutes
        - name: ServiceUrls__UserDbHandler__BaseUrl
          valueFrom:
             configMapKeyRef:
              name: service-url-config
              key: userDbHandler
        - name: ServiceUrls__StreamDbHandler__BaseUrl
          valueFrom:
             configMapKeyRef:
              name: service-url-config
              key: streamDbHandler
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
