apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service
  labels:
    app: stream-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
      - name: stream-service
        image: bugapeti/streamservice:latest # TODO: update with your image
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        # Add other environment variables as needed, similar to StreamDbHandler
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
