apiVersion: v1
kind: Service
metadata:
  name: db-management
  labels:
    app: db-management
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: db-management
