apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-management-deployment
  labels:
    app: db-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-management
  template:
    metadata:
      labels:
        app: db-management
    spec:
      containers:
      - name: db-management
        image: bugapeti/databasemanagementservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-connection-string
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
