apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-db-handler
  labels:
    app: stream-db-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-db-handler
  template:
    metadata:
      labels:
        app: stream-db-handler
    spec:
      containers:
      - name: stream-db-handler
        image: bugapeti/streamdbhandler-k8s:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-connection-string
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-connection-string
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret-key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-audience
        - name: Jwt__ExpiryMinutes
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-expiry-minutes
        - name: Rtmp__Server
          valueFrom:
            configMapKeyRef:
              name: rtmp-config
              key: rtmp-server
        - name: Rtmp__StreamKeyPrefix
          valueFrom:
            configMapKeyRef:
              name: rtmp-config
              key: stream-key-prefix
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
