kubectl delete -f UserDbHandler/k8s/
kubectl delete -f ViewerService/k8s/
kubectl delete -f FollowerService/k8s/
kubectl delete -f StreamDbHandler/k8s/
kubectl delete -f AuthService/k8s/
kubectl delete -f StreamService/k8s/
kubectl delete -f Database/PostgreSQL/
kubectl delete -f Database/Redis/
kubectl delete -f Nginx-RTMP/k8s
kubectl delete -f DatabaseManagementService/k8s
kubectl delete -f Client/k8s/