@host = http://localhost:8006

### Health Check
GET {{host}}/health
Accept: application/json

### Get Migration Status
GET {{host}}/api/migration/pending
Accept: application/json

### Run Migration
POST {{host}}/api/migration/migrate
Accept: application/json
