apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: bugapeti/analyticsservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-connection-string
        - name: ConnectionStrings__Redis
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: redis-connection-string
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret-key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-audience
        - name: Jwt__ExpiryMinutes
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-expiry-minutes
        - name: Analytics__CacheExpiryMinutes
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: cache-expiry-minutes
        - name: Analytics__SampleDataEnabled
          valueFrom:
            configMapKeyRef:
              name: analytics-config
              key: sample-data-enabled
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
