apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer-service
  labels:
    app: viewer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viewer-service
  template:
    metadata:
      labels:
        app: viewer-service
    spec:
      containers:
      - name: viewer-service
        image: bugapeti/viewerservice-k8s:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret-key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-audience
        - name: Jwt__ExpiryMinutes
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-expiry-minutes
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
