apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  secret-key: eW91ci0yNTYtYml0LXNlY3JldC1rZXktaGVyZS1hdC1sZWFzdC0zMi1jaGFycw== # Base64 encoded secret key
  service-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZXJ2aWNlLWFjY291bnQiLCJqdGkiOiJlMDQ2Nzk0Yi1lODY5LTRmODEtOWY3YS0xNWE5Yjk1MGU3ODUiLCJyb2xlIjoiU2VydmljZSIsIm5iZiI6MTc0NTQ0NDAwOCwiZXhwIjoxNzQ4MDM2MDA4LCJpc3MiOiJzdHJlYW1pbmctcGxhdGZvcm0iLCJhdWQiOiJzdHJlYW1pbmctdXNlcnMifQ.qQgxEqq12c6wObgr83_7tDoMOY1O-jaPQNjHRppCjUg