apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower-service
  labels:
    app: follower-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follower-service
  template:
    metadata:
      labels:
        app: follower-service
    spec:
      containers:
      - name: follower-service
        image: bugapeti/followerservice-k8s:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: Jwt__SecretKey
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: secret-key
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-issuer
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-audience
        - name: Jwt__ExpiryMinutes
          valueFrom:
            configMapKeyRef:
              name: auth-config
              key: jwt-expiry-minutes
        # Add additional environment variables and secrets as needed
