apiVersion: apps/v1
kind: Deployment
metadata:
  name: follower-service
  labels:
    app: follower-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: follower-service
  template:
    metadata:
      labels:
        app: follower-service
    spec:
      containers:
      - name: follower-service
        image: bugapeti/followerservice:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        # Add additional environment variables and secrets as needed
