apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
    spec:
      containers:
      - name: nginx-rtmp
        image: bugapeti/nginx-rtmp-k8s:latest
        ports:
        - containerPort: 1935
        - containerPort: 8080